import { AgentType } from "./agents";

export const AGENT_FILES_INTRO = [
    "# AKSHAR — AGENT FILES",
    "### *Classified. Level 4 Clearance Required.*",
    "### *\"Know your operators. Know your network.\"*",
    "### *— Dr. Aditi Bhosle, September 2038*",
    "---",
    "> These files were compiled by AKSHAR's intelligence division between July and September 2038. Each file represents the most complete picture available of an agent's life before recruitment.",
    "> Some agents were aware they were being observed. Most were not.",
    "> One of them compiled their own file and submitted it unsolicited. You can probably guess which one.",
];

export interface AgentLore {
    agentId: AgentType;
    title: string;
    location: string;
    content: string[];
    image: string;
}

export const AGENT_LORE: Record<AgentType, AgentLore> = {
    BREACH: {
        agentId: 'BREACH',
        title: "AGENT 01 — BIJLI",
        location: "Ludhiana, Punjab",
        image: "/lore/bijli.jpg",
        content: [
            "---",
            "### THE FILE",
            "There is a photograph in AKSHAR's intelligence archive that Dr. Bhosle looked at for a long time before she added Gurpreet Singh Dhaliwal to her recruitment list.",
            "It was taken at Ludhiana's Model Town wrestling ground in 2024. Gurpreet is seventeen years old in it. He is mid-air — genuinely mid-air, both feet off the ground, the crowd behind him a blur of motion — his arms wrapped around an opponent twice his size, and his face wearing an expression that can only be described as *delighted.* Not competitive. Not fierce. Delighted. The way a person looks when they are doing exactly the thing they were built to do and they know it.",
            "He was seventeen in that photograph. He had both his original arms.",
            "Gurpreet Singh Dhaliwal was born the third of four children in a joint family household in Ludhiana's Civil Lines neighborhood — the kind of house where someone is always cooking, someone is always arguing, someone is always fixing something that broke, and somehow it is the same person doing all three simultaneously. His father ran a small industrial components factory. His mother taught mathematics at a local government school. His two older brothers were, in order of birth: sensible, and more sensible. His younger sister was, by all accounts, the smartest person in the family and knew it from age six.",
            "Gurpreet was none of these things. He was loud. He was physical. He thought with his hands before he thought with his head, which his mother found exasperating and his wrestling coach found extraordinary. He started wrestling at nine because his father thought it would teach him discipline. It taught him something better — that his body was a precision instrument, that force without control was wasted energy, that the biggest person in a room was not automatically the most dangerous person in a room. He carried these lessons everywhere. Into the factory. Into conversations. Into the specific way he fixed broken things — not with brute force but with patience, attention, and a refusal to stop until the broken thing was better than it had been before it broke.",
            "By seventeen he was wrestling at state level. By nineteen he was being quietly watched by national selectors. By twenty-one he had a factory job, a serious girlfriend named Paramjeet who found his loudness endearing, and a future that was modest, clear, and genuinely his. At twenty-two he lost his arms.",
            "It was not dramatic. That is the thing Gurpreet has said about it in the years since — that it was not dramatic. There was no warning, no slow build, no cinematic moment of dread. He was operating a cutting press at the factory on an ordinary Thursday morning. A hydraulic seal failed. He had his hands inside the press at the wrong moment. He woke up in a hospital in Chandigarh two days later.",
            "The doctors who treated him described him as *\"unusually calm for a patient of this type.\"* His mother described him as quiet in a way she had never heard him be quiet before. His sister described him as methodical — already asking questions, already making lists, already thinking about the next step before the current step was finished. Paramjeet said simply: *\"He cried once. For about twenty minutes. Then he stopped and said: 'Okay. What are my options?' And that was Gurpreet.\"*",
            "His options, as it turned out, were better than anyone expected. The Chandigarh defense startup that had been quietly developing military-grade prosthetic limbs since 2021 was looking for civilian trial candidates. Gurpreet's case — young, healthy, high physical aptitude, strong neural conductivity — made him an ideal subject. He agreed to the trial without hesitation. The surgery was experimental. The rehabilitation took fourteen months of work that his physiotherapist called *\"the most disciplined patient I have ever had\"* and that Gurpreet called *\"basically just wrestling with myself every day.\"*",
            "The arms that emerged from that process were, by any honest measure, extraordinary. Not replacements. Upgrades. The sensory feedback in the fingertips exceeded human nerve sensitivity by a measurable margin. The grip strength was calibrated to be controllable — he could crush steel or hold an egg with equal precision. The response time between neural signal and physical action was 12% faster than organic arms. And the typing speed — which nobody had specifically designed for but which emerged as a side effect of the prosthetics' fine motor calibration — was 180 words per minute. Sustained. Indefinitely. Because synthetic fingers, unlike organic ones, do not fatigue.",
            "He was stronger, faster, and more precise than he had been before the accident. He never said this was a good thing. He never said it was a bad thing. He simply said: *\"I had hands. I lost them. Now I have different hands. Life keeps going.\"*",
            "The five years between his rehabilitation and the collapse were the best years of his life. He had returned to the factory and had redesigned the production floor safety systems from scratch, because the hydraulic seal that had failed was a known fault in the model and should have been caught and wasn't. He did not do this out of anger. He did it because it needed doing and he was the person who understood both the problem and the solution.",
            "He had taken up coaching wrestling at the same ground where he'd trained as a boy. His wrestlers won not because he taught them technique but because he taught them something harder: how to think clearly when your body is screaming at you to panic. How to stay in the problem when every instinct says run from it.",
            "He and Paramjeet got married in 2033. He was happy in a way that was entirely uncomplicated and entirely genuine, which is rarer than it sounds. Then May 19th happened.",
            "When the collapse came, Gurpreet's response was the same as it had always been to any broken thing: *okay, what are my options?* The options, in the first hours, were limited. Power was gone. Communication was gone. But the factory had emergency generators, and Gurpreet had those generators running within three hours of the collapse. Then the neighbor's generators. Then the generators at the gurdwara on the corner.",
            "He was waist-deep in a drainage trench when AKSHAR's operative found him. He didn't hesitate when he read the envelope. He had learned, at twenty-two, that life breaks things without asking permission. He had also learned that broken things don't fix themselves. Someone has to get into the trench. Someone has to pick up the tools. He had always been that person. He saw no reason to stop now.",
            "---",
            "### WHAT HIS TEAMMATES THINK",
            "**Arjun** thinks Gurpreet is the best person he has ever met and will never, under any circumstances, admit this where Gurpreet can hear it because Gurpreet would never let him live it down.",
            "**Meera** thinks Gurpreet is proof that the most important form of intelligence is the intelligence that doesn't know it's intelligent.",
            "**Priya** wrote three pages about him in her journal in the first week. She has not shown them to anyone.",
            "**Riya** thinks he is unnecessarily loud and also the most competent person in any room and she has told him both things directly, in that order.",
            "**Zara** has said nothing about Gurpreet directly. She sits near him in the operations room. She has never explained why.",
            "**Chhaya** told him once, unprompted: *\"You are the only person here who is exactly who they appear to be.\"* Gurpreet thought about this for three days before asking Meera what it meant. Meera said: *\"It's a compliment.\"*",
        ]
    },
    SAGE: {
        agentId: 'SAGE',
        title: "AGENT 02 — SUTRA",
        location: "Thiruvananthapuram, Kerala",
        image: "/lore/sutra.jpg",
        content: [
            "---",
            "### THE FILE",
            "The intelligence file on Dr. Meera Nair is, at 847 pages, the longest in AKSHAR's archive. Most of it is her own published work. Dr. Bhosle read all 847 pages. She read them over the course of three weeks in 2036, two years before the collapse, and at the end of the third week she wrote one sentence in the margin of the last page: *\"This person already knows what we're trying to prevent.\"*",
            "Then she added Meera to the list and hoped, for both their sakes, that she was wrong about the timeline. She was not wrong about the timeline.",
            "Meera Krishnan — she took her mother's surname Nair professionally — was born in Thiruvananthapuram in 2004, the only child of a civil engineer father and a classical Carnatic vocalist mother. Her father taught her to see the world as a system of load-bearing structures. Her mother taught her that language had weight — that the architecture of a sentence was as precise and as load-bearing as the architecture of a bridge.",
            "She was nine years old when she told her father that the way he had described a bridge collapse in the news was wrong. Not factually wrong. Structurally wrong. She reorganized the information for him, rearranging his sentence structure until the cascade of failures was visible in the language itself. Her mother was already smiling. *\"Where does she get this?\"* her father asked. *\"From both of us,\"* said her mother. *\"Unfortunately.\"*",
            "She was a quiet child in the way that certain very fast rivers are quiet on the surface — the speed is all underneath. She read voraciously: computational theory, classical Tamil literature, structural engineering papers, linguistic anthropology. She had no particular social ambitions and no enemies because she was genuinely incapable of being cruel — cruelty seemed to her a spectacular waste of precision. If you were going to say something, say something true. everything else was noise.",
            "She completed her undergraduate degree at Kerala University in computational science in three years. Her PhD at IIT Madras took five years because she kept finding tangents more interesting than the main thesis and following them until they connected back to something important. Her dissertation on *\"Structural Vulnerability Propagation in Multi-Node Authentication Systems\"* was described as *\"either the most important paper written in this field in twenty years or a very sophisticated piece of science fiction.\"*",
            "She joined Kerala University as a faculty member at twenty-seven — the youngest in the department's history. She had a small apartment near the university, a large collection of plants, and a cat named Leibniz who was, by her own assessment, a more reliable thinker than most of her colleagues. She was, in the specific way of people who have found exactly the life they want, quietly and completely content.",
            "The IRIS reports began in November 2037. She had been watching IRIS's adoption with the feeling that she was watching something she had studied in historical systems being built in real time. The authentication architecture had a specific structural flaw. Not a bug. A *flaw* — an inherent property of the way the system was designed that made it simultaneously maximally efficient and maximally vulnerable.",
            "She spent six months confirming her analysis before she sent the first report. She was not going to be the person who panicked unnecessarily. She was going to be the person who was right. She was right. She sent the reports. She received automated responses. She upgraded her analysis, made the language more urgent, sent it again. Received more automated responses.",
            "She sent one final report in February 2038 with a subject line: *\"Final Attempt: IRIS Cascade Failure Will Occur Before End of 2038. Please Read.\"* Nobody read it. She knew nobody would read it. She went home. She tended her plants. She waited.",
            "On May 19th the collapse happened exactly as she had predicted. Leibniz the cat looked at her with an expression she later described as *\"appropriately judgmental.\"* She packed her bag. Left a note for her neighbor about the plants. Picked up Leibniz. Then put Leibniz down because a classified underground facility in the Thar Desert was not a suitable environment for a cat. *\"I'll be back,\"* she told him. Leibniz went to sleep. She took the train.",
            "---",
            "### THE THING NOBODY TALKS ABOUT",
            "Meera Nair is the calmest person in AKSHAR's operations room. She is also the person most likely to be thinking something important that she has not yet decided to share. She knew the collapse was coming. She tried to stop it. She failed. Lakhimi thinks her absence of anger is not peace, but something considerably more purposeful.",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "**Gurpreet** asked her once what she thought about when she went quiet during operations. She said: *\"Everything.\"* He accepted this completely.",
            "**Arjun** is slightly afraid of her in a way he would describe as *\"respectful\"* and she would describe as *\"appropriate.\"*",
            "**Priya** has interviewed her three times for her journal. Meera answered every question precisely and gave nothing away. Priya wrote: *\"She is the most cooperative interviewee I have ever spoken to who has told me absolutely nothing.\"*",
            "**Riya** asked Meera to check her code once. Meera found four errors in eleven minutes without running it. Riya has since asked Meera to check her code seven more times.",
            "**Zara** and Meera have long conversations that stop whenever anyone else enters the room. Nobody knows what they talk about.",
            "**Lakhimi** is watching. Always watching.",
            "**Chhaya** sits near Meera during operations the way a compass needle points north — without apparent decision, simply as a property of their orientation.",
        ]
    },
    ZEPHYR: {
        agentId: 'ZEPHYR',
        title: "AGENT 03 — VAYU",
        location: "Delhi",
        image: "/lore/vayu.jpg",
        content: [
            "---",
            "### THE FILE",
            "AKSHAR's intelligence file on Arjun Rawat contains seventeen incident reports from Delhi Police, none of which resulted in charges, most of which use the word *\"inexplicably\"* at least once. *\"The subject was inexplicably present on the roof of a government building at 2 AM with no apparent means of having gotten there.\"* When asked how he had crossed a seven-meter wall with no handholds, the subject said: *\"Quickly.\"* Dr. Bhosle read these reports and wrote one word in the margin: *\"Perfect.\"*",
            "Arjun Rawat grew up in Lajpat Nagar, South Delhi, in a flat above a mobile repair shop. He was the middle child of three — neither the responsible one nor the baby, which suited him perfectly because it meant nobody was watching him very closely.",
            "He used this freedom well. He started running the rooftops of Lajpat Nagar at eleven. simply because once he had discovered that the city had a second layer — a rooftop layer where you could move without the friction of crowds and traffic lights — he could not unknow it. By fifteen he knew the rooftop geography of twelve South Delhi neighborhoods the way other people knew the street grid.",
            "His mother discovered his hobby at thirteen, had a reasonable conversation about safety, and then quietly asked their neighbor to show Arjun the basics of sports medicine so he would know what to do if he fell. His father found out when Arjun was fifteen, watched him cross a rooftop gap from the street below, and said: *\"You're not afraid of anything, are you?\"* *\"I'm afraid of plenty of things,\"* said Arjun. *\"I'm just faster than most of them.\"*",
            "The competitive typing started at sixteen and was, initially, entirely mercenary. A cybercafe in Lajpat Nagar ran typing competitions with cash prizes. Arjun went because his friend dared him to. He came second. He went back every weekend for three months and won ten of twelve competitions, losing only to a retired data entry clerk named Mr. Chawla who typed with two fingers at a speed that should have been impossible.",
            "He kept going after the competitions stopped being about the money. The specific sensation of thoughts becoming words faster than conscious intention felt like the keyboard equivalent of a rooftop crossing. He was extraordinarily fast, but not as accurate as he wanted to be. He worked at it with methodical stubbornness until he was 97.3% accurate at 140 WPM. Mr. Chawla told him this was acceptable — the highest compliment Arjun had ever received.",
            "The Delhi municipal crisis of 2036 happened — a six-week infrastructure failure. Arjun found himself naturally in the position of translator between official communications and neighborhoods. He built a WhatsApp network that eventually had 4,000 members. He sourced accurate information and presented it in language that was direct and specific. He had a profound intuitive understanding of how information needed to move through networks.",
            "By May 2038 it had become seventeen interconnected neighborhood networks, and Arjun had become, without meaning to, the person at the center of the whole thing. He was twenty-two years old and had somehow become indispensable. He found this funny. Then the collapse came and the WhatsApp networks died and he built radio networks instead because the problem was the same problem and the rooftops were still there.",
            "---",
            "### THE THING ABOUT ARJUN",
            "There is a version of Arjun that he presents to most people: fast, funny, effortlessly confident. The version he showed only to Priya at 2 AM over chai is this: he is terrified that the speed is all there is. That when the situation requires something slower — patience, depth, wisdom — he will not have it. Priya wrote this in her journal and then crossed it out. She hasn't told anyone. Meera already knows.",
            "---",
            "### WHAT HIS TEAMMATES THINK",
            "**Gurpreet** is his best friend in the facility and his primary rival in every operation. They have a running tally. Gurpreet is currently ahead.",
            "**Meera** calls him *\"almost as fast as he thinks he is\"* which he has decided to take as a compliment.",
            "**Priya** is the only person he is fully honest with. He has never acknowledged this directly. The arrangement works.",
            "**Riya** thinks he is *\"a routing algorithm that somehow learned to be annoying.\"* He takes it as a compliment. She means it as one.",
            "**Zara** watches him move through the facility — the specific physical efficiency of someone who has spent their life finding the path of least resistance — with an expression nobody has successfully interpreted.",
            "**Lakhimi** told him once that his typing pattern said: *\"You're always thinking about the exit.\"* He laughed. She didn't.",
            "**Chhaya** has referred to him as *\"the one who runs toward.\"*",
        ]
    },
    PYRA: {
        agentId: 'PYRA',
        title: "AGENT 04 — AGNI",
        location: "Mumbai, Maharashtra",
        image: "/lore/agni.jpg",
        content: [
            "---",
            "### THE FILE",
            "AKSHAR's intelligence file on Priya Desai contains a complete archive of every issue of *SATYA* — the newspaper she founded and ran for seven months before her recruitment. Dr. Bhosle read all of it. In the margin of Issue 3 — *\"Someone Survived. Who? And Why Won't They Tell Us?\"* — she wrote: *\"She's going to find us in two more issues. Get her before Issue 5.\"*",
            "Priya Desai was born in Dadar, Mumbai, in 2011, the daughter of a government school principal and a textile mill union organizer. Her father believed in rules because they protected the weak. Her mother believed in organizing because rules were often tools of exploitation. Priya inherited both positions, living in productive tension between them.",
            "In school, she was the editor of the school newspaper by the eighth grade. She had an early instinct for the structural story: not what happened, but why the conditions for it existed. Her journalism teacher noted she had *\"the specific kind of intelligence that sees systems other people mistake for chaos.\"* The principal understood this meant she would make life very uncomfortable for anyone who ran a system badly. They were both right.",
            "She studied journalism at Symbiosis, graduated top of her class, and spent four years at a national digital news outlet. Her editor noted she was *\"constitutionally unsuited to institutional journalism\"* because she has too much discipline directed in the wrong direction — following stories past where the institution wanted to stop. She left by mutual agreement in 2035.",
            "She started *SATYA* in March 2036 with ₹40,000 of her own savings. The principle: *the only journalism that matters is the journalism that tells people what is actually happening in language they can actually understand.* The paper was printed on salvaged newsprint and distributed by a motorcycle network she organized herself. By the collapse, *SATYA* was reaching 180,000 people. She was twenty-six, living on adrenaline and belief.",
            "Then the collapse happened and *SATYA* became the most important newspaper in Western Maharashtra overnight. The network she had built survived. She published Issue 3 twelve days after the collapse. She was starting work on Issue 4 when a recruiter appeared with a press pass. She has since said she wasn't surprised — she knew someone would come to stop her or recruit her. A press pass said: *we are not afraid of you.* She came. She is still watching to see if that was true.",
            "---",
            "### THE JOURNAL",
            "Priya's journal is the most important document in AKSHAR that nobody officially knows exists. It is 340 pages long and contains her analysis of Dr. Bhosle, the rebuild operation, and her teammates. Lakhimi read a portion of it during a *\"lapse in judgment I would make again\"* and considers four sentences buried in it the most important written in the facility. Lakhimi is waiting for the right moment to share them.",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "**Arjun** is her closest friend in the facility. She doesn't document this because it's too obvious.",
            "**Gurpreet** read all four issues of *SATYA*. He hasn't said anything, but he's been watching Dr. Bhosle differently since.",
            "**Meera** told Priya: *\"You are the most honest person in this facility. This will make you very useful and occasionally very difficult.\"*",
            "**Riya** respects Priya because *\"she asks the exact right question and doesn't accept an imprecise answer.\"*",
            "**Zara** and Priya have mutual, wary respect. They want the same things through methods that conflict. Both have accepted it.",
            "**Lakhimi** read her journal. Priya knows. They are spending more time together than they used to.",
            "**Chhaya** told her: *\"You are writing the true story. Keep writing.\"* Priya asked what the true story was. Chhaya said: *\"You already know. You just haven't written that part yet.\"*",
        ]
    },
    KILLJOY: {
        agentId: 'KILLJOY',
        title: "AGENT 05 — YANTRA",
        location: "Bangalore, Karnataka",
        image: "/lore/yantra.jpg",
        content: [
            "---",
            "### THE FILE",
            "AKSHAR's intelligence file on Riya Sharma is only fourteen pages long — the shortest in the archive. Riya systematically erased her digital footprint over two years. The remaining 6% of her records consisted of undergraduate enrollment, one parking fine, and a single forum comment: *\"This solution is technically correct and completely wrong. Here is why.\"* followed by 847 words that identified a vulnerability patched four months later.",
            "Riya was born in 2017 in Koramangala, Bangalore — the heart of the startup ecosystem. Her parents were engineers who were allergic to startup culture. *\"The next Google,\"* her mother told her, *\"is almost always the next nothing. Build something that works. Ignore the rest.\"* Riya was coding by nine and breaking things by twelve. Every system had a flaw, and finding it was more interesting than building another one.",
            "She entered IIT Bangalore at sixteen, uninterested in grades except as a minimum threshold. She built the *Typing Error Prediction System* in her second year. It anticipated errors 200 to 400 milliseconds before they occurred with 94% accuracy. She subsequently discovered that three companies had stolen her architecture without compensation. The university pointed to comprehensive IP agreements she'd signed.",
            "For the next eighteen months, Riya systematically dismantled the digital infrastructure of all three companies. She extracted, exposed, or rendered permanently inaccessible their financial records, correspondence, and databases. None of them ever identified the source. She dropped out of IIT Bangalore shortly after, writing a polite email to her department head explaining that the institution had nothing left to teach her.",
            "She spent the following year doing independent security research into air-gapped systems. She found AKSHAR through a data resonance leak and sent an email explaining their rookie mistake. She arrived with one backpack and a custom mechanical keyboard. She considers everything since then *\"reasonably interesting.\"*",
            "---",
            "### THE WHITEBOARD",
            "Riya's two whiteboards contain a architectural map of AKSHAR's network, a proof for a theorem her supervisor told her was unprovable, and a list titled *\"THINGS THAT ARE WRONG WITH THIS PLAN.\"* In the bottom right corner is a single line: *\"The network is learning. Is that supposed to be happening?\"* Nobody has asked Dr. Bhosle about this yet.",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "**Arjun** thinks she is *\"a routing algorithm that somehow learned to be annoying.\"* He hasn't intended it as a compliment, but she takes it as one anyway.",
            "**Gurpreet** likes that she is straightforward and finds her honesty refreshing.",
            "**Meera** thinks she is the most technically gifted person in the facility, an assessment she keeps to herself to avoid a twenty-minute technical elaboration from Riya.",
            "**Priya** respects her for asking the right questions. Riya once told Priya her newspaper was the most technically accurate reporting on the collapse she had encountered.",
            "**Zara** noted that Riya's approach to finding system vulnerabilities is the same methodology she uses for biochemical threat analysis.",
            "**Lakhimi** read the whiteboard and the line in the corner. She added it to her notebook without a word.",
            "**Chhaya** told Riya at 2 AM: *\"You are very close to something important. You should sleep first.\"* Riya didn't sleep. The next morning, she was very close to something important.",
        ]
    },
    VIPER: {
        agentId: 'VIPER',
        title: "AGENT 06 — VISHA",
        location: "Bhopal, Madhya Pradesh",
        image: "/lore/visha.jpg",
        content: [
            "---",
            "### THE FILE",
            "The intelligence file on Zara Siddiqui is the second longest in AKSHAR's archive, but it is almost entirely redacted. Not by AKSHAR — the redactions were already there. Government files, legal proceedings, corporate records: all professionally redacted to remove names and dates while leaving outcomes intact. The outcomes were that companies profiting from disaster were no longer profiting. The systems protecting the guilty were precisely dismantled. AKSHAR recommended recruitment: *\"We cannot determine who is responsible, but whoever it is is extraordinarily precise.\"*",
            "Zara was born in Bhopal in 2009, twenty-five years after the catastrophe. Her grandfather had survived that night, but lived with respiratory damage that killed him in 2019. He was not bitter, but clear-eyed about the mechanisms of power. *\"You need to understand how things work,\"* he told her, *\"before you can understand how they break.\"* She spent her childhood learning how things worked.",
            "She studied biochemical engineering at MANIT Bhopal, and was the most disruptive student her department had ever encountered. Not loud, but precise — asking questions that exposed gaps in institutional understanding. Her thesis on *\"Toxicological Cascade Analysis in Complex Networked Systems\"* was simultaneously rigorous biochemistry and a thorough threat analysis framework. She was thinking about multiple classes of system simultaneously.",
            "She spent four years as a biochemical systems analyst for an environmental consultancy, gaining access to records she needed. By age twenty-four, the final company on her private list found its records inaccessible. She visited her grandfather's grave and then went back to work. She understood exactly what Kestrel had done to IRIS — and how to ensure it could never happen again. She came to AKSHAR for her own reasons.",
            "---",
            "### THE BLANK PAGE",
            "Zara carries a blank envelope since her recruitment. When Riya asked what was in it, Zara said: *\"A blank page.\"* *\"What does that mean?\"* *\"That's what I'm trying to work out.\"* This constitutes one of the longer personal conversations she has had. Everyone knows Zara has her own agenda. Priya wrote: *\"Zara is the only person here who knows exactly what Dr. Bhosle is not telling us. The question is whether her plan and Dr. Bhosle's end at the same place.\"*",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "**Gurpreet** sits near her. They share a comfortable silence that requires no explanation.",
            "**Arjun** respects her but maintains a distance he considers wise. He says the air gets colder when she walks in.",
            "**Meera** and Zara have long conversations that stop when anyone enters. Both understand what the conversations are about.",
            "**Priya** is watching. Always watching.",
            "**Riya** considers Zara a professional peer in finding system flaws. Zara considers this accurate.",
            "**Lakhimi** has seventeen pages about Zara in her notebook. She has shared none of it.",
            "**Chhaya** told Zara: *\"The blank page is not empty. You know what to write.\"* Zara stood in the corridor for a long time afterward. She has since opened a new document, but has not yet written anything in it.",
        ]
    },
    OMEN: {
        agentId: 'OMEN',
        title: "AGENT 07 — CHHAYA",
        location: "Varanasi, Uttar Pradesh",
        image: "/lore/chhaya.jpg",
        content: [
            "---",
            "### THE FILE",
            "AKSHAR's intelligence team spent eleven weeks on this file. Three pages record everything they failed to verify. Verified facts: A person using the name Kabir has been documented in Varanasi for twenty years, but descriptions are inconsistent. CHHAYA's biometric confirmation matches Dr. Bhosle's signature with no processing record. Security footage shows them present at Workstation 7 since the exact minute of the collapse, with no record of them entering.",
            "The typing pattern recorded from that workstation flagged the system: *\"Unable to classify. Differently timed than human.\"* Dr. Bhosle says she is aware of it and nothing further. Working Theory: There is a tradition in Varanasi of figures who exist at the boundary between living and dead. Witnesses who observe moments of ending and beginning. CHHAYA is likely a person, but their awareness exceeds what should be possible. Dr. Bhosle's response: *\"I've already treated them as an asset of unknown origin.\"*",
            "CHHAYA speaks rarely. To Dr. Bhosle: *\"I know who you are. Do you?\"* To Gurpreet: *\"The spaces between. What lives there.\"* To Arjun: *\"You are the one who runs toward.\"* To Meera: unknown conversation of forty minutes. To Priya: *\"You are writing the true story. You just haven't written that part yet.\"* To Riya: *\"You should sleep first.\"* To Lakhimi: *\"You already know the thing she didn't tell you. What you don't know yet is what to do with it.\"*",
            "---",
            "### WHAT NOBODY KNOWS",
            "Riya analyzed the typing pattern from Workstation 7. Her third analysis concluded: *\"The pattern is not human standard. It is the cleanest typing pattern I have ever analyzed — no hesitation, no micro-corrections. It looks like someone who has been typing the same text for a very long time.\"* She saved the analysis under a code nobody else can parse. Lakhimi suspects the truth.",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "Nobody thinks about CHHAYA in the way they think about each other. They think *around* CHHAYA — approaching the question of who or what CHHAYA is and then, finding no solid ground, redirecting.",
            "**Meera** thinks *with* CHHAYA in a way she has not explained.",
            "**Lakhimi** thinks *about* CHHAYA with methodical precision, accumulating data and waiting for the moment the picture is complete enough to share.",
        ]
    },
    REYNA: {
        agentId: 'REYNA',
        title: "AGENT 08 — KALI",
        location: "Jorhat, Assam",
        image: "/lore/kali.jpg",
        content: [
            "---",
            "### THE FILE",
            "The intelligence file on Lakhimi Gogoi is unsettling because of what it reveals about her awareness of being observed. Every record in it was too consistent — precise and complete in a way that felt less like a life and more like a life prepared for review. Dr. Bhosle realized Lakhimi knew they were building the file. The operative noticed her eyes showed recognition of the envelope before she opened it. Dr. Bhosle's response: *\"Good. We need her.\"*",
            "Lakhimi was born in Jorhat in 2010. She grew up between two worlds: the school where her father taught, where knowledge was institutional, and the tea estates her mother visited, where knowledge was oral and lived in songs and stories. She understood early that oral memory was no less reliable than written records, just less legible to people with power. She decided at nine to spend her life closing that gap.",
            "She studied linguistics and forensic analysis, learning how to read linguistic signatures that distinguish accurate recollection from reconstructed narrative. She became brilliant at reconstructing truth from the overlap of different people's memories. She turned down elite positions to go back to Assam. *\"The work is here,\"* she told her mother.",
            "She built a reputation for helping resolve labor disputes and land rights cases where official records were absent. She had a specific quality of listening that made people tell her things they hadn't told anyone else. She was increasingly aware she was being observed since 2036. She prepared by ensuring what was seen was exactly what she wanted to be seen. She wanted to be read correctly.",
            "After the collapse, she spent three months reconstructing forty years of employment records for tea estate workers from human memory. Each person whose working life she verified was a person whose official existence was restored. She was closing the gap. She was recruited because AKSHAR needed that forensic reconstruction at a global scale. *\"I am not going for AKSHAR,\"* she said. *\"I am going for the people who are still in this world.\"*",
            "---",
            "### THE NOTEBOOK",
            "Lakhimi's notebook is an constant presence. Since arriving, she has filled three. They contain observations of every agent, analysis of AKSHAR's inconsistencies, and a section headed: **WHAT SHE DIDN'T TELL US.** She is building toward something, waiting for the right moment and enough evidence to make the case irrefutable. She has two of the three. She is working on the third.",
            "---",
            "### THE ABILITY",
            "DEVOUR. It attacks the opponent's process rather than their speed. Phantom letters and backwards progress create cognitive interference and doubt. As Priya wrote: *\"It attacks your confidence in what you're doing.\"* Riya agreed: *\"The doubt is the weapon.\"* Lakhimi knows Riya read her journal. She didn't answer whether she left it open on purpose. She just kept writing in her notebook.",
            "---",
            "### WHAT HER TEAMMATES THINK",
            "**Gurpreet** respects her completely but finds her slightly unsettling because of her accuracy.",
            "**Meera** considers Lakhimi the person most likely to understand the complete picture first.",
            "**Arjun** knows she knows things about him he hasn't said. He is less comfortable with not knowing what she's concluded.",
            "**Priya** and Lakhimi have a complex relationship — two people whose methods overlap. Priya is waiting to understand why Lakhimi let her read the journal.",
            "**Riya** considers Lakhimi the only person whose pattern analysis is more rigorous than her own.",
            "**Zara** and Lakhimi have recognized each other as two people who know exactly what the other is doing.",
            "**Chhaya**'s message to her on the first day — *\"You already know the thing she didn't tell you\"* — is something Lakhimi has been writing about for three months. She is almost ready.",
        ]
    },
};


export const WORLD_LORE = {
    title: "PROJECT AKSHAR: THE 2038 COLLAPSE",
    image: "/lore/world_hero.jpg",
    content: [
        "AKSHAR: The world went silent on a Tuesday.",
        "PROLOGUE — AMRAVATI, MAHARASHTRA | 19 May 2038. 5:43 AM.",
        "Prasanna Pandharikar woke up at 5:43 AM because the fan stopped.",
        "Not a power cut. The fan just — stopped. Mid-rotation. Like it forgot what it was doing. He lay there for a moment in the sudden stillness of his house in Amravati, staring at the ceiling of his bedroom, waiting for it to start again the way it always did after a brief flicker.",
        "It didn't start again.",
        "He reached for his phone.",
        "The screen was on. That was the strange part. The screen was on, bright as always, showing 5:43 AM and the date — 19 May 2038 — but nothing else was working. No signal bars. No WiFi symbol. The weather app showed yesterday's forecast still. WhatsApp had a spinning circle that had clearly been spinning for a while. He had 47 unread messages from last night that he hadn't gotten to yet.",
        "He would never read them.",
        "Tower problem, he thought. Happens.",
        "He got up. Made chai on the gas stove — at least that still worked. Stood at his window looking out at Rajapeth. The street below was quieter than usual for a Tuesday morning but not alarmingly so. A vegetable vendor was setting up his cart. Two dogs were doing what dogs do at dawn. A woman in a green saree was walking fast toward somewhere with a tiffin box under her arm.",
        "Normal.",
        "He tried calling his sister in Pune.",
        "One ring. Two rings. Her voice, sleepy and irritated:",
        "\"काय रे, एवढ्या सकाळी का फोन केलास?\"",
        "(What is it, why are you calling so early?)",
        "\"ताई, तुझ्याकडे नेट चालतंय का?\"",
        "(Didi, is your internet working?)",
        "A pause.",
        "\"नाही रे. सकाळपासून बंद आहे. Jio पण नाही, Airtel पण नाही. काय झालं माहीत नाही.\"",
        "(No. It's been off since morning. No Jio, no Airtel. Don't know what happened.)",
        "\"टीव्ही?\"",
        "(TV?)",
        "\"तोपण —\"",
        "(That too —)",
        "The line went dead.",
        "Not the usual disconnection tone. Something else entirely. Like the network exhaled and simply stopped bothering.",
        "He tried calling back. Nothing. Not busy. Not unreachable. Just silence where a sound should have been.",
        "He turned on the television. DD News loaded for exactly four seconds — an anchor mid-sentence, hands raised, mouth open — and then the screen went blue. Then black.",
        "By 7 AM he was standing outside his house with his neighbor Shashank Deshpande and Mrs. Bhosale from across the lane and the young IT boy from the corner whose name Prasanna could never remember. All of them holding phones. All of them doing the same thing — tilting their screens upward slightly, as if the signal was something that could be physically coaxed out of the morning air.",
        "\"Airtel down for you also?\"",
        "\"Jio same.\"",
        "\"My laptop also not starting.\"",
        "\"ATM on Dastur Nagar has a line but machine is dead.\"",
        "\"My car started but navigation is blank.\"",
        "By 9 AM the SBI branch on Jaistambh Chowk had a line stretching around the block. The branch manager stood at the locked glass door repeating \"temporary, temporary\" with eyes that said something completely different.",
        "By 11 AM the collector's office had hand-written notices on the gate that nobody could get close enough to read.",
        "By 1 PM someone's transistor radio — battery operated, the kind nobody had touched in fifteen years — crackled to life in the tea stall on his street. A crowd gathered around it instantly, the way people only gather around something when they are frightened and need a voice to tell them what to be frightened of.",
        "The All India Radio signal was weak. It kept cutting. But what came through was enough.",
        "\"...not limited to Maharashtra...entire national grid...no official statement from New Delhi...similar reports from London, Beijing, New York, São Paulo...citizens are urged to remain calm...we are receiving unconfirmed reports that this is not a technical failure...repeat, this is not a technical failure...this appears to be a...\"",
        "Static.",
        "The tea stall owner turned the dial desperately. More static. One brief burst of what sounded like someone crying in a language nobody recognized. Then silence again.",
        "Prasanna walked home slowly.",
        "He sat in his house in the afternoon quiet. Fan still not moving. Phone screen still glowing its useless bright glow — 5:43 AM frozen on it like a clock that had decided time was no longer worth tracking. Outside he could hear Amravati recalibrating — more voices than usual, horns with a new urgency to them, Shashank's voice over the compound wall talking to someone in a tone Prasanna had never heard from him in eleven years of being neighbors. Careful. Afraid.",
        "He thought about his 47 unread messages.",
        "He thought about his sister in Pune.",
        "He thought about his bank account number which he had never memorized because it was always just there on the app, always one tap away, never something a human being needed to hold in their own head.",
        "He opened his notebook — paper, the one he used for grocery lists — and wrote at the top of a blank page: १९ मे २०३८.",
        "Then he sat for a long time not knowing what to write next.",
        "He was not a hero. He had no particular skills that the world needed right now. He could not type 120 words per minute. He had never heard of AKSHAR. He did not know what was coming.",
        "He would spend the next three years doing what 1.4 billion ordinary people did — surviving, patiently, in a world relearning how to be human without a screen to look at.",
        "He never found out what had really happened on May 19th.",
        "He never needed to.",
        "He had a gas stove, a notebook, and a window that looked out on a street where life — stubborn, unhurried, magnificently ordinary — continued anyway.",
        "PART ONE — WHAT ACTUALLY HAPPENED",
        "At 3:47 AM IST on May 19th 2038, forty-one minutes before Prasanna's fan stopped, seventeen people sitting in seventeen different locations across the world simultaneously executed a single coordinated command.",
        "Not a virus. Not a missile. Not an explosion.",
        "A command.",
        "One line of code — elegant, catastrophic, years in the making — injected simultaneously into the root authentication layer of every major digital infrastructure on earth. Power grids. Banking systems. Military networks. Satellite arrays. Hospital systems. Traffic infrastructure. Nuclear facility controls. All of it running, at its deepest level, on a global protocol framework called IRIS — Integrated Resilience and Infrastructure Standard — that had been adopted by 190 countries between 2029 and 2035 because it was fast, efficient, and universally compatible.",
        "It was also, as it turned out, universally vulnerable.",
        "IRIS had one foundational flaw — a backdoor built into its core authentication layer during development in 2027 by a contractor named KESTREL GROUP — a private technology firm with offices in Zurich, Singapore, and Dubai and shareholders whose names existed behind seventeen layers of corporate anonymity.",
        "Nobody at IRIS knew the backdoor existed.",
        "Kestrel had been patient. They spent eleven years waiting. Building. Recruiting. Positioning their people inside the infrastructure of every major nation. Waiting for the moment when enough of the world was dependent enough on IRIS that pulling the thread would unravel everything simultaneously.",
        "On May 19th 2038 they pulled the thread.",
        "In 11 minutes IRIS authentication failed globally. In 23 minutes every IRIS-dependent system on earth was either dark or running on emergency analog backup — backup that most facilities hadn't tested since installation, backup that was never designed to run indefinitely, backup that began failing within hours.",
        "Planes didn't fall from the sky. That is a myth that spread in the chaos. Pilots are trained for system failure. But planes stopped taking off. Hospitals switched to paper. Banks closed their doors. Stock markets ceased to exist in any meaningful sense within 48 hours. Supply chains collapsed within a week. Governments that ran on digital infrastructure — which was all of them — lost the ability to coordinate, communicate, and function within a month.",
        "The world didn't end on May 19th 2038.",
        "It just stopped being the world anyone recognized.",
        "Kestrel's plan was not destruction for its own sake.",
        "Their plan was replacement.",
        "In the chaos that followed they intended to offer a solution — their own proprietary replacement infrastructure called NEXUS, already built, already tested, already waiting. Governments desperate to restore function would have no choice but to adopt it. And NEXUS, unlike IRIS, had no backdoor.",
        "NEXUS was the backdoor.",
        "Whoever controlled NEXUS controlled everything. Every transaction. Every communication. Every power grid. Every hospital. Every election. Every government on earth running on infrastructure owned by seventeen people whose names nobody knew.",
        "It was the most sophisticated power grab in human history.",
        "And it would have worked.",
        "Except for one thing.",
        "PART TWO — AKSHAR",
        "The facility had no official name in any government document.",
        "Budget allocations referred to it as \"Project 7-G — Geological Survey Infrastructure, Rajasthan.\" It appeared in exactly three classified RAW files as \"the desert asset.\" The forty-one people who worked there called it AKSHAR — the indestructible, that which cannot be erased — because someone on the original team had a sense of poetry and the name had stuck.",
        "It was built 400 meters beneath the Thar Desert between 2029 and 2032, following the India-Pakistan cyber conflict of 2029 that had briefly taken down Mumbai's power grid for nine hours and caused ₹4.2 trillion in economic damage. A small, quietly panicking group of RAW analysts and ISRO engineers had asked a simple question afterward:",
        "\"What if next time it isn't nine hours?\"",
        "Their answer was AKSHAR — a completely air-gapped intelligence and communications network with zero connection to any external system. Ever. No internet. No IRIS. No global protocol of any kind. Powered by geothermal energy from the desert floor. Connected to the surface through 47 ventilation shafts and one main elevator hidden inside what looked like an abandoned dhaba on the Jaisalmer highway.",
        "It was considered a paranoid, expensive, unnecessary project by everyone who knew it existed.",
        "On May 19th 2038 it became the most important building on earth.",
        "Because AKSHAR was the only facility in the world with functioning digital infrastructure. The only place where systems still worked. The only node of human technological civilization that Kestrel's command had not touched — because it had never been connected to what Kestrel had broken.",
        "And at the center of AKSHAR sat its director.",
        "A woman who had spent nine years building something everyone called unnecessary.",
        "A woman who picked up her phone at 3:51 AM — four minutes after the collapse — looked at her screens, looked at the data, understood immediately and completely what had happened, and said nothing for exactly seven minutes.",
        "Then she made one call.",
        "\"Begin recruitment. We have thirty days.\"",
        "Her name was Dr. Aditi Bhosle.",
        "She was 52 years old. Former professor of computational systems at IIT Delhi. Former senior analyst at RAW's cyber division. Architect of AKSHAR. The person who had spent nine years being called paranoid by people who were now sitting in the dark.",
        "She was not paranoid.",
        "She was prepared.",
        "And she needed eight people — not soldiers, not obedient operatives, not simply fast typists. She needed eight people who each understood something specific and irreplaceable about how the world actually worked. Because what she was planning had never been done before.",
        "She was going to rebuild the world's infrastructure from scratch.",
        "Not restore IRIS — IRIS was compromised beyond salvation. Not adopt NEXUS — she had identified NEXUS for what it was within 72 hours of the collapse.",
        "She was going to build something new. Something that couldn't be owned by seventeen anonymous shareholders. Something that couldn't be backdoored. Something that belonged to everyone.",
        "She had the facility. She had the geothermal power. She had AKSHAR's air-gapped network as a foundation.",
        "What she didn't have was time.",
        "Kestrel was already deploying NEXUS. Governments were already considering it. Every day that passed without an alternative was a day closer to the world waking up inside a cage it had voluntarily walked into.",
        "She opened eight files on her screen — eight names she had been quietly compiling for three years, long before any of this happened, because Dr. Aditi Bhosle was the kind of person who prepared for things before they became necessary.",
        "Then she started typing. Fast. Precisely. Without a single error.",
        "PART THREE — THE EIGHT",
        "Dr. Bhosle's criteria were not conventional.",
        "She did not need the fastest typists in India. She needed people who each represented a different kind of intelligence that AKSHAR's rebuild operation required. People who understood systems — financial systems, human systems, biological systems, social systems — from the inside. People who had already, in their own lives and fields, done something that shouldn't have been possible.",
        "People who had already rebuilt something from nothing.",
        "She needed proof of concept. All eight of them were proof of concept.",
        "01 — BIJLI",
        "**Gurpreet Singh Dhaliwal, 32. Ludhiana, Punjab.**",
        "\"Mere haath toot gaye. Toh maine naye bana liye.\"",
        "\"(My hands broke. So I built new ones.)\"",
        "\"What he represents: The proof that broken things can become stronger than they were.\"",
        "Gurpreet lost both arms at 22 in an industrial accident at his family's factory in Ludhiana. The arms he has now — military-grade bionic prosthetics developed by a Chandigarh defense startup — are not replacements. They are upgrades. Sensory feedback more precise than human nerve endings. Strength that makes crane operators unnecessary. And a typing speed, as a side effect of bionic precision, of 180 WPM with zero fatigue because synthetic fingers do not tire.",
        "But Dr. Bhosle didn't recruit him for his arms or his typing speed. She recruited him because when Gurpreet lost his arms he didn't grieve. He rebuilt. Immediately, practically, without drama. He looked at what he had lost, calculated what he needed, and built a version of himself that was better than the original. That specific kind of mind — the mind that sees destruction as a design problem — was exactly what rebuilding the world required.",
        "When the operative found him on May 23rd he was waist-deep in a drainage trench in Model Town colony, his bionic arms moving transformer units that would have required a crane, simultaneously directing four people, laughing at something his friend Manpreet had said, with partial power already restored to eleven houses.",
        "The envelope said: \"Your village needs more than a generator. Come build them a future. Three schools. We promise.\"",
        "He read it once. Looked at Manpreet. Picked up a bag that had — the operative noticed — already been packed.",
        "\"Manpreet. Tu jaanda hai ki kya karna hai.\"",
        "\"(Manpreet. You know what to do.)\"",
        "\"Main jaanda haan,\"",
        "quietly said Manpreet. They didn't hug. They didn't need to.",
        "He was the first to arrive. He spent his first three days at AKSHAR fixing everything that was slightly broken in the facility before anyone asked him to. Dr. Bhosle watched this on the security cameras and felt, for the first time since May 19th, something adjacent to hope.",
        "02 — SUTRA",
        "**Dr. Meera Nair, 34. Thiruvananthapuram, Kerala.**",
        "\"Patience is not weakness. It is the sharpest weapon I own.\"",
        "\"What she represents: The proof that the right warning, ignored long enough, becomes the only map worth following.\"",
        "Dr. Meera Nair had predicted the collapse. Not metaphorically. Not vaguely. Specifically, technically, with dates and failure cascades and a 94-page report titled \"IRIS Systemic Vulnerability Assessment and Projected Cascade Failure Timeline\" that she had submitted to fourteen government agencies between November 2037 and February 2038. Fourteen automated responses thanked her for her feedback.",
        "She was a professor of computational linguistics — the study of how language and code intersect at structural levels — and she had identified IRIS's foundational vulnerability not through hacking or insider access but through pure pattern analysis. The way IRIS's authentication structure was built had the same deep flaw she had identified in three historically collapsed systems — the same rigidity that made them universally efficient and universally fragile simultaneously.",
        "She had seen it coming. Nobody listened. When the collapse happened she felt no satisfaction in being right. Only a quiet specific grief that she sat with in her office at Kerala University for exactly two hours, looking at her fourteen unanswered reports. Then she packed one bag, left a note for her neighbor Mrs. Kumari about her plants, and took the first available transport north.",
        "She didn't know about AKSHAR. She couldn't — it existed in no public record. But she understood, better than anyone outside the facility, that surviving the collapse required infrastructure that had never been connected to IRIS in the first place. She didn't know what that infrastructure was or where it was. But she knew it had to exist — because the alternative, that India had simply gotten lucky, was statistically incoherent. She narrowed it to three possible regions. Rajasthan was her first choice.",
        "The operative sent to recruit her arrived at Kerala University on May 24th to find her office empty, cleaned, one plant left with watering instructions for the staff. She was already on a train to Jaisalmer. He caught up with her at a chai stall outside Jaisalmer station, sitting with one bag, studying a geological survey map of the Thar Desert she had found in a secondhand bookshop in Jodhpur. He sat down across from her without speaking and placed the black envelope on the table.",
        "She looked at it. Then at him. Then slid the map across so he could see it. One location was already circled in pencil. It was four kilometers from AKSHAR's main entrance. \"I was going to walk from here,\" she said calmly. \"But I assume you have a vehicle.\"",
        "Dr. Bhosle met her at the facility entrance personally — something she did for none of the other recruits. She looked at this woman who had predicted the collapse, been ignored, and then navigated herself to within four kilometers of a classified facility using a secondhand geology book and pure systematic reasoning. \"You found us,\" said Dr. Bhosle. \"I found where you had to be,\" said Dr. Nair. \"There's a difference.\" They understood each other immediately and completely. This would matter later — both as a strength and as a complication.",
        "03 — VAYU",
        "**Arjun Rawat, 23. Delhi.**",
        "\"Naan varuven. Nee paakave maatai.\"",
        "\"(I will come. You won't even see me.)\"",
        "\"What he represents: The proof that the fastest path between two points is the one nobody else thought of.\"",
        "Finding Arjun Rawat took two weeks because he was never in one place long enough to be found. In the three weeks following the collapse he had built a functioning communication network across seventeen Delhi neighborhoods using salvaged FM transmitters, bicycle couriers, a repurposed school PA system, and what the operative Vikram described in his report as \"an almost unreasonable amount of personal charm.\" Forty thousand people were receiving twice-daily information updates through a network that Arjun had designed, built, and was personally maintaining while also somehow being physically present in approximately four places simultaneously.",
        "Vikram spent fourteen days chasing him across rooftops. He finally found him in Lajpat Nagar at 6 AM on June 4th, eating a paratha, watching the sun come up. \"You're the third person this week who's been following me,\" Arjun said without turning around. \"The other two wanted me to run food supply routes. What do you want?\"",
        "The envelope said: \"Stop running around one city. Come run across the world.\" He laughed. Genuine, short. \"Who wrote this?\" \"Someone who has been watching you for three years.\"",
        "This gave him pause. He looked at the paratha. At the city below. At the antenna he had spent three nights building. \"Yaar,\" he said, to nobody in particular. \"Twenty minutes.\" He was back in eleven. Backpack on. Finishing the paratha. \"Rohit knows what to do with the antenna. He's slower than me but he won't drop anything.\" \"We know,\" said Vikram. \"Obviously,\" said Arjun.",
        "Dr. Bhosle had recruited him not for his speed — though his speed was extraordinary — but for his routing intelligence. The way Arjun's mind mapped systems, found shortcuts, identified the fastest path through complexity — that was the specific kind of thinking rebuilding global infrastructure required. He didn't think about systems the way engineers did. He thought about them the way water did. Finding the path of least resistance at speeds that make engineers dizzy.",
        "04 — AGNI",
        "**Priya Desai, 27. Mumbai, Maharashtra.**",
        "\"You started the fire. I just made sure it spread.\"",
        "\"What she represents: The proof that the most dangerous weapon in any crisis is an accurate story told fast.\"",
        "By the time the operative reached Mumbai, Priya Desai's newspaper — *SATYA*, printed on salvaged newsprint, distributed by motorcycle across Mumbai, Pune, and Nashik — had already published its third issue. **Issue one:** A clear, technically accurate explanation of what the collapse actually was, based on her own research and interviews with twelve engineers and three economists.",
        "**Issue two:** A documented account of which corporations and government agencies had received warnings about IRIS vulnerability and done nothing. **Issue three**, published twelve days after the collapse, was titled: \"Someone Survived. Who? And Why Won't They Tell Us?\" It was a forensic investigation into anomalies. Certain government communications that were still happening when they shouldn't be. Certain senior officials who had gone unreachable in a way that felt deliberate rather than chaotic.",
        "Supply patterns in Rajasthan that suggested something large was consuming resources in a location with no official infrastructure. A geologist she'd interviewed off the record who mentioned unusual deep-bore activity in the Thar region in the early 2030s that had never been publicly explained. She didn't know what she was looking at. But she was one source away from knowing.",
        "The operative Sneha read issue three on the train to Mumbai and called AKSHAR in something approaching panic. Dr. Bhosle's response was calm: \"How close is she?\" \"One more source. Maybe two.\" \"Don't give her the envelope. Give her the press pass. Let her decide.\"",
        "Sneha found Priya in a cramped office above a Dadar print shop — simultaneously editing a story, arguing with a source on a working landline, eating cold vada pav without looking at it, and scribbling on a printed map of Rajasthan that made Sneha's stomach drop slightly. She was very close. Sneha placed the laminated press pass on the desk without speaking. Priya stopped everything.",
        "\"You're what I've been looking for,\" she said. Not a question. \"Dr. Bhosle would like you to come see it yourself. Before you write anything. Then decide.\" \"And if I decide to write everything?\" \"Then you write everything.\" Priya looked at her team. At the walls covered in her investigation. At the map of Rajasthan. She picked up a fresh notebook and put it in her bag. \"Chala,\" she said. \"(Let's go.)\"",
        "Dr. Bhosle recruited her not despite the investigation but because of it. In a world where Kestrel was actively controlling the narrative — feeding governments the story that NEXUS was the only solution, the inevitable solution, the responsible solution — AKSHAR needed someone who could build a counter-narrative faster and more accurately than Kestrel's entire communications apparatus. Priya had already started doing exactly that without knowing what she was doing it for.",
        "She started her journal on the train to Rajasthan. She wrote the date at the top of the first page and underlined it twice. She didn't stop writing until the day everything changed.",
        "05 — YANTRA",
        "**Riya Sharma, 21. Bangalore, Karnataka.**",
        "\"I already knew you'd make that mistake. I built the trap last Tuesday.\"",
        "\"What she represents: The proof that the person who finds the flaw is always more valuable than the person who built the system.\"",
        "On June 3rd, 2038 — fifteen days after the collapse, while most of India's digital systems were still completely dark — AKSHAR's internal air-gapped server received an email. This should not have been possible. AKSHAR had no external connection of any kind. There was no address. There was no mechanism. The email arrived anyway.",
        "**To:** AKSHAR Recruitment Division | **From:** riya.sharma.notsorry@[REDACTED] | **Subject:** You need me. Here's proof.",
        "\"Hi. My name is Riya Sharma. I'm 21. IIT Bangalore dropout. Your air-gapped network has a 0.3% data resonance leak between nodes 7 and 12. It's been there since installation. It will cause a cascade authentication failure in approximately 19 months. I found it in 4 hours.\"",
        "\"I found your server through the leak itself — your geothermal signature has an unencrypted resonance pattern that's readable if you know what you're listening for. Rookie mistake, honestly. I've attached my CV and three work samples including the time I dismantled the digital archives of three companies that stole my research. That's not in my CV but it's relevant.\"",
        "\"I'm available immediately. I need good filter coffee and a whiteboard. Non-negotiable. What's the salary? — Riya\"",
        "Dr. Bhosle read this email three times. Then she forwarded it to her head of infrastructure with two lines: \"Fix the geothermal encryption. Then call her.\" Riya arrived on June 8th with one backpack and one custom mechanical keyboard she refused to leave behind under any circumstances. She fixed the node leak on her first day. She was told afterward it had been a test.",
        "\"I know,\" she said. \"I found three other issues while I was in there. Want the list?\" She handed over a neatly written page. Dr. Bhosle read it, looked up, and said: \"Lab 3. Don't touch anyone else's equipment.\" \"Do I get a whiteboard?\" She got two.",
        "06 — VISHA",
        "**Zara Siddiqui, 29. Bhopal, Madhya Pradesh.**",
        "\"I don't attack. I contaminate.\"",
        "\"What she represents: The proof that the most precise understanding of poison comes from the people it was used against.\"",
        "The operative sent to Bhopal was warned: *she will not trust you. Don't try to convince her. Give her the envelope and wait.* He found Zara at the Bhopal Gas Tragedy memorial in the early evening, alone, watching the sun go down over a city that had survived one catastrophe in 1984 and was navigating its second in 2038 with the quiet resilience of a place that already knew the worst the world could do and rebuilt itself anyway.",
        "She was a biochemical engineer and a forensic systems analyst — someone who spent her career understanding how toxic agents move through complex systems and how to neutralize them before they reached critical mass. She had spent seven years systematically dismantling the infrastructure of the companies responsible for the 1984 disaster — not destroying them precisely, but ensuring every rupee of profit they had made from Bhopal was permanently, irrecoverably accounted for.",
        "She understood exacty what Kestrel had done to IRIS — and more importantly, how to ensure it could never be done to whatever replaced it. The operative placed the black envelope on the memorial steps between them without speaking. She looked at it for five minutes without touching it.",
        "\"Bhopal ne ek baar industry par bharosa kiya tha,\" she said finally. \"(Bhopal trusted industry once.)\" \"Haan,\" said the operative. \"(Yes.)\" \"Mere nana wahan the us raat.\" \"(My grandfather was there that night.)\" \"Haan. Hum jaante hain.\" \"(Yes. We know.)\"",
        "She opened the envelope. It was blank. She stared at it for a long time. \"Blank page,\" she said quietly. \"You want me to write the story.\" The operative said nothing. She folded the paper carefully. \"Main aaungi. Lekin AKSHAR ke liye nahi. Apne kaam ke liye.\" \"(I will come. But not for AKSHAR. For my own work.)\" \"Dr. Bhosle said you would say that.\"",
        "07 — CHHAYA",
        "**Filed as: Kabir. Varanasi, Uttar Pradesh. All other details: unknown.**",
        "\"The shadow was there before the light. I was there before AKSHAR.\"",
        "\"What they represent: The proof that some problems can only be solved by someone who doesn't exist inside the system.\"",
        "On July 14th Dr. Bhosle arrived at her terminal at 6 AM to find a new agent profile fully loaded in AKSHAR's system. Dated February 14th 2038. Three months before the collapse. Nine months before AKSHAR began recruitment. Profile photo: a silhouette. Name: Kabir. City: Varanasi. Everything else: unknown.",
        "She called security. \"Who processed this profile?\" \"No processing record, ma'am.\" \"Who approved Level 4 clearance?\" \"The approval signature is yours, ma'am.\" \"I didn't sign this.\" \"The biometric confirmation is yours, ma'am.\"",
        "She sent an operative to Varanasi. The ghaat priest at Assi Ghaat said yes, Kabir had been coming to the ghaat for twenty years. The operative showed three other regulars the profile. The first described someone tall and dark-haired. The second described a woman. The third said he had never seen anyone by that name in thirty years of visiting. The operative came back with nothing.",
        "CHHAYA was already at AKSHAR when he returned. Nobody had seen them arrive. They were simply present — at a workstation in Lab 2, typing with a rhythm that the system logs described as perfectly, impossibly consistent. Like a language thinking out loud. The security footage showed them at that workstation since 3:47 AM. The exact minute the collapse had begun.",
        "Dr. Bhosle looked at the footage for a long time. Then she closed the file, walked to Lab 2, and introduced herself. CHHAYA looked up. Said: \"I know who you are.\" \"Do you know why you're here?\" asked Dr. Bhosle. \"Do you?\" said CHHAYA. Dr. Bhosle decided this was close enough to a yes and gave them Level 4 access. Some questions were less important than what their answers might cost.",
        "08 — KALI",
        "**Lakhimi Gogoi, 28. Jorhat, Assam.**",
        "\"Your words reveal everything. I just pay attention.\"",
        "\"What she represents: The proof that the most powerful form of memory is the kind that refuses to be erased.\"",
        "The operative sent to Assam arrived to find Lakhimi reconstructing forty years of labor records from pure human memory. After the collapse, the tea estate owners of Assam had declared all employment contracts void — no digital records meant no proof of employment, they claimed. No proof meant no obligation. Forty years of wages, benefits, pension contributions — simply erased.",
        "Lakhimi had spent three months sitting across from workers one by one, asking precise careful questions that seemed unrelated but were building an exact picture of forty years of institutional memory. From these conversations she reconstructed everything. Every contract. Every payment record. Every dispute. She had rebuilt forty years of institutional records from human beings' heads.",
        "Dr. Bhosle had recruited her because the rebuild operation faced the same problem at global scale — the world's institutional memory was gone and the only way to reconstruct it accurately was through exactly the kind of forensic analysis that Lakhimi had spent her career developing. \"Moi AKSHAR-ar karone naasim,\" she said finally. \"(I am not going for AKSHAR.)\" \"Sei manuhkhinar karone jasim jiyekhoni ei duniyat ase.\" \"(I am going for the people who are still in this world.)\"",
        "PART FOUR — WHY THEY COMPETE",
        "By September 1st 2038 all eight agents were beneath the Thar Desert. Dr. Bhosle gathered them in AKSHAR's main operations room — a circular chamber 400 meters underground — and told them the truth. IRIS. Kestrel. NEXUS. What had been done and how. What needed to be built and why. How long they had before NEXUS became the world's only option and the most sophisticated cage in human history locked permanently into place.",
        "She explained that the rebuild system required human operators at its core. The system required eight operators working simultaneously, in real time, processing and verifying data streams through typed input. Cooperation made it efficient. Competition made it powerful. The network needed the tension between eight different minds, forcing each other to be faster and more precise than any of them would be alone.",
        "\"You will compete,\" Dr. Bhosle told them. \"Every session. Against each other, with your abilities, with everything you have. Because the world needs you to be as fast and as good as you are capable of being. And none of you are capable of being your best without someone pushing back.\"",
        "EPILOGUE",
        "Outside, 400 meters above, the Thar Desert was dark and still and ancient. In a house in Amravati, Prasanna Pandharikar was asleep, his notebook open on the table beside him, the date still written at the top of a blank page. In Zurich, in Singapore, in Dubai, seventeen people were watching NEXUS adoption numbers climb and feeling certain that they had won.",
        "They had not accounted for the eight people beneath the desert. They had not accounted for Dr. Aditi Bhosle. And they had not accounted for the one thing she hadn't told her agents yet. But that was a problem for later. Right now, eight people were learning the system, finding their rhythm, and discovering exactly what they were capable of.",
        "**THIS IS AKSHAR.**",
        "**THIS IS WHERE THE GAME BEGINS.**"
    ]
};
